# ===== Config padrão (todos os profiles) =====
app.email.remetente=no-reply@exemplo.com
app.email.assunto-padrao=Boas-vindas
app.email.copia-oculta=auditoria@exemplo.com
app.limite-requisicoes=100
app.feature.beta=false

# ===== Dev (quarkus dev) =====
%dev.app.email.remetente=dev@local.test
%dev.app.feature.beta=true
%dev.quarkus.log.level=DEBUG

# ===== Test (./mvnw test) =====
%test.app.email.remetente=test@fake.io
%test.app.limite-requisicoes=10

# ===== Prod (java -jar) =====
# Em prod a ideia é NÃO colocar valor sensível aqui.
# Defina via env var: APP_EMAIL_REMETENTE=... APP_LIMITE_REQUISICOES=...
%prod.quarkus.log.level=INFO
