quarkus.http.port=8080

# Build time: nome do app
quarkus.application.name=demo-native

# Native: incluir arquivos do resources/ no binario
quarkus.native.resources.includes=dados.json,config/**

# Native: args extras (mostrar stack trace de erro no build)
quarkus.native.additional-build-args=-H:+ReportExceptionStackTraces

# Native: usar container build (nao precisa GraalVM local)
quarkus.native.container-build=true

# Run time: pode ser sobrescrito por env var sem recompilar
greeting.message=Ola do Native!
