# Verificacao (validar tokens que chegam)
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://meusite.dev

# Assinatura (emitir tokens no /login)
smallrye.jwt.sign.key.location=privateKey.pem

# Garante que os .pem sejam empacotados no jar/native
quarkus.native.resources.includes=publicKey.pem,privateKey.pem

# Em prod: troque por variavel de ambiente, ex:
# SMALLRYE_JWT_SIGN_KEY=${vault:secret/jwt#private}
