# ---- Servidor gRPC ----
quarkus.grpc.server.port=9000
# Sem TLS pra dev (em prod, configure certificado)
quarkus.grpc.server.plain-text=true

# ---- Cliente gRPC chamado "saudacao" ----
# Bate com @GrpcClient("saudacao") no SaudacaoResource
quarkus.grpc.clients.saudacao.host=localhost
quarkus.grpc.clients.saudacao.port=9000

# ---- HTTP (REST) ----
quarkus.http.port=8080
