# Health
quarkus.smallrye-health.root-path=/q/health
quarkus.smallrye-health.ui.always-include=true

# Mostra mais detalhes no /q/health (dados do withData)
quarkus.smallrye-health.ui.enable=true

# Datasource pra o BancoHealthCheck funcionar (H2 em memoria)
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:h2:mem:demo

# Micrometer / Prometheus
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics

# Tags globais aplicadas em todas as metricas
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.system=true
