# --- Info da API exibida no Swagger UI ---
quarkus.smallrye-openapi.info-title=API de Pedidos
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API REST para gerenciamento de pedidos da loja exemplo.
quarkus.smallrye-openapi.info-terms-of-service=https://exemplo.com/termos
quarkus.smallrye-openapi.info-contact-name=Time Backend
quarkus.smallrye-openapi.info-contact-email=dev@loja.com
quarkus.smallrye-openapi.info-contact-url=https://exemplo.com/contato
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html

# --- Caminho do schema (default /q/openapi) ---
quarkus.smallrye-openapi.path=/q/openapi

# --- Swagger UI ---
# Por padrão o Swagger UI só aparece em dev/test. Vamos ligar também em prod:
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.swagger-ui.title=Pedidos - Documentação
quarkus.swagger-ui.theme=flattop
