# ===== Producer: REST -> Kafka (tópico "pedidos") =====
mp.messaging.outgoing.pedidos-out.connector=smallrye-kafka
mp.messaging.outgoing.pedidos-out.topic=pedidos
mp.messaging.outgoing.pedidos-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# ===== Transformer: consome "pedidos", emite em "pedidos-processados" =====
mp.messaging.incoming.pedidos-in.connector=smallrye-kafka
mp.messaging.incoming.pedidos-in.topic=pedidos
mp.messaging.incoming.pedidos-in.group.id=grupo-transformer
mp.messaging.incoming.pedidos-in.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
mp.messaging.incoming.pedidos-in.value.deserializer.type=com.exemplo.pedidos.Pedido

mp.messaging.outgoing.pedidos-processados-out.connector=smallrye-kafka
mp.messaging.outgoing.pedidos-processados-out.topic=pedidos-processados
mp.messaging.outgoing.pedidos-processados-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# ===== Consumer final: lê "pedidos-processados" e loga =====
mp.messaging.incoming.pedidos-processados-in.connector=smallrye-kafka
mp.messaging.incoming.pedidos-processados-in.topic=pedidos-processados
mp.messaging.incoming.pedidos-processados-in.group.id=grupo-consumer-final
mp.messaging.incoming.pedidos-processados-in.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
mp.messaging.incoming.pedidos-processados-in.value.deserializer.type=com.exemplo.pedidos.Pedido

# Pra falhas permanentes — Dead Letter Topic
mp.messaging.incoming.pedidos-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.pedidos-in.dead-letter-queue.topic=pedidos-dlq

# Dev Services sobe Kafka sozinho — sem precisar de kafka.bootstrap.servers em dev
quarkus.http.port=8080
